name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Get version
        run: echo "::set-output name=version::$(cat build.gradle | grep 'version = "' | sed 's/.$//' | sed 's/version = "//')"
        id: version
      - name: Get short commit id
        id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Build ${{ steps.version.outputs.version }}-c${{ steps.commit.outputs.short }}
          tag_name: c${{ steps.commit.outputs.short }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload the jar and add it to the release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/easyenchanting-${{ steps.version.outputs.version }}-all.jar
          asset_name: easyenchanting-${{ steps.version.outputs.version }}.jar
          asset_content_type: application/jar